config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get 'user_levels/edit', as: 'edit_user_level'
  patch 'user_levels/update', as: 'update_user_level'

  post 'matchmaking', to: 'matchmaking#create', as: 'create_matchmaking'
  delete 'matchmaking', to: 'matchmaking#destroy', as: 'destroy_matchmaking'

  resources :duel_problems, only: [:index]

  resources :duels do
    resources :submissions, only: %i[new create]
    get 'summary', on: :member, to: 'summaries#show'
  end

  resources :problem_sets do
    resources :problems, except: %i[index show]
  end

  resources :custom_duels, only: %i[index new create show] do
    resources :participants, only: %i[create destroy], controller: 'custom_duel_participants'
  end

  get 'history', to: 'user_duels#index', as: 'history'
  get 'join/:id', to: 'custom_duel_join#show', as: 'join_custom_duel'
  patch 'start/:id', to: 'custom_duel_start#update', as: 'start_custom_duel'

  get 'settings', to: 'settings#show', as: 'settings'
  get 'leaderboard', to: 'leaderboard#index', as: 'leaderboard'
  get 'leaderboard/:level', to: 'leaderboard#show', as: 'level_leaderboard'
  get 'static_pages/index'

  root 'static_pages#index'
end

app/models/problem_set.rb
# frozen_string_literal: true

class ProblemSet < ApplicationRecord
  has_many :problems, dependent: :destroy
  has_many :duels
  belongs_to :user, optional: true

  validates :name, :complexity, presence: true

  enum :complexity, { beginner: 0, intermediate: 1, advanced: 2, expert: 3 }

  def detailed_name
    "#{name} (#{complexity})"
  end
end

app/controllers/problem_sets_controller.rb
# frozen_string_literal: true

class ProblemSetsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_problem_set, only: %i[show edit update destroy]

  def index
    @problem_sets = current_user.problem_sets
  end

  def show
    @problem_set = ProblemSet.find(params[:id])
    @problems = @problem_set.problems
  end

  def new
    @problem_set = current_user.problem_sets.new
  end

  def edit; end

  def create
    @problem_set = current_user.problem_sets.new(problem_set_params)
    if @problem_set.save
      redirect_to @problem_set
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @problem_set.update(problem_set_params)
      redirect_to problem_sets_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @problem_set.destroy

    redirect_to problem_sets_path
  end

  private

  def problem_set_params
    params.require(:problem_set).permit(:name, :complexity)
  end

  def set_problem_set
    @problem_set = ProblemSet.find(params[:id])
  end
end

app/views/problem_sets/_form.html.erb
<%= form_for @problem_set do |f| %>
  <%= render 'shared/errors', resource: @problem_set %>

  <div class="mb-3">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', required: true %>
  </div>

  <div class="mb-3">
    <%= f.label :complexity %>
    <%= f.select :complexity, User.levels.keys, {}, class: 'form-select' %>
  </div>

  <div class="mb-3">
    <%= f.submit "Save", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/problem_sets/edit.html.erb
<div class="row row-cols-2 mb-3">
  <div class="offset-3">
    <div class="mb-3">
      <h3>Edit problem set</h3>
    </div>

    <%= render 'form' %>
  </div>
</div>

app/views/problem_sets/index.html.erb
<%= link_to 'Create new problem set', new_problem_set_path, class: 'btn btn-primary mb-3' %>

<table class="table table-borderless">
  <thead>
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Complexity level</th>
    <th>Problems count</th>
    <th>Created at</th>
    <th>Actions</th>
  </tr>
  </thead>
  <% @problem_sets.each do |problem_set| %>
    <tr>
      <td><%= problem_set.id %></td>
      <td><%= problem_set.name %></td>
      <td><%= problem_set.complexity %></td>
      <td><%= problem_set.problems.size %></td>
      <td><%= date_format(problem_set.created_at) %></td>
      <td>
        <%= link_to 'Details', problem_set_path(problem_set), class: 'btn btn-primary' %>
        <%= link_to 'Edit', edit_problem_set_path(problem_set), class: 'btn btn-primary' %>
        <%= link_to 'Delete', problem_set_path(problem_set), data: { turbo_method: :delete }, class: 'btn btn-danger' %>
      </td>
    </tr>
  <% end %>
</table>

app/views/problem_sets/new.html.erb
<div class="row row-cols-2 mb-3">
  <div class="offset-3">
    <div class="mb-3">
      <h3>Create new problem set</h3>
    </div>

    <%= render 'form' %>
  </div>
</div>

app/views/problem_sets/show.html.erb
<h3><%= @problem_set.name %> |
  <%= @problem_set.complexity %> |
  <%= link_to 'Create new problem', new_problem_set_problem_path(@problem_set), class: 'btn btn-primary' %>
</h3>

<table class="table table-borderless">
  <thead>
  <tr>
    <th>ID</th>
    <th>description</th>
    <th>Points</th>
    <th>Choices</th>
    <th>Answer</th>
    <th>Actions</th>
  </tr>
  </thead>
  <% @problem_set.problems.each do |problem| %>
    <tr>
      <td><%= problem.id %></td>
      <td><%= problem.description %></td>
      <td><%= problem.points %></td>
      <td><%= problem.choices %></td>
      <td><%= problem.answer %></td>
      <td>
        <%= link_to 'Edit', edit_problem_set_problem_path(@problem_set, problem), class: 'btn btn-primary' %>
        <%= link_to 'Delete', problem_set_problem_path(@problem_set, problem), data: { turbo_method: :delete }, class: 'btn btn-danger' %>
      </td>
    </tr>
  <% end %>
</table>