config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get 'user_levels/edit', as: 'edit_user_level'
  patch 'user_levels/update', as: 'update_user_level'

  post 'matchmaking', to: 'matchmaking#create', as: 'create_matchmaking'
  delete 'matchmaking', to: 'matchmaking#destroy', as: 'destroy_matchmaking'

  resources :duel_problems, only: [:index]

  resources :duels do
    resources :submissions, only: %i[new create]
    get 'summary', on: :member, to: 'summaries#show'
  end

  resources :problem_sets do
    resources :problems, except: %i[index show]
  end

  resources :custom_duels, only: %i[index new create show] do
    resources :participants, only: %i[create destroy], controller: 'custom_duel_participants'
  end

  get 'history', to: 'user_duels#index', as: 'history'
  get 'join/:id', to: 'custom_duel_join#show', as: 'join_custom_duel'
  patch 'start/:id', to: 'custom_duel_start#update', as: 'start_custom_duel'

  get 'settings', to: 'settings#show', as: 'settings'
  get 'leaderboard', to: 'leaderboard#index', as: 'leaderboard'
  get 'leaderboard/:level', to: 'leaderboard#show', as: 'level_leaderboard'
  get 'static_pages/index'

  root 'static_pages#index'
end

app/controllers/leaderboard_controller.rb
# frozen_string_literal: true

class LeaderboardController < ApplicationController
  def index; end

  def show
    @users_ranking = RanksQuery.call(limit: 10, level: params[:level])

    return unless current_user
    return unless current_user.level == params[:level]

    @user_rank = UserRankRecordQuery.call(current_user)

    return if @user_rank.rank < 10

    @users_ranking = @users_ranking.to_a
    @users_ranking << @user_rank
  end
end

app/helpers/leaderboard_helper.rb
# frozen_string_literal: true

module LeaderboardHelper
  def active_level(user)
    return 'beginner' unless user

    user.level
  end
end

app/views/leaderboard/_level_leaderboard.html.erb
<div class="tab-pane fade show <%= 'active' if active %>" id="<%= level %>" role="tabpanel" aria-labelledby="<%= level %>-tab">
  <%= turbo_frame_tag "#{level}_leaderboard", src: level_leaderboard_path(level: level) %>
</div>

app/views/leaderboard/index.html.erb
<div class="row row-cols-2 mb-5 text-center">
  <div class="offset-3 mb-5">
    <div class="col">
      <ul class="nav nav-tabs" id="myTab" role="tablist">

        <% User.levels.keys.each do |level| %>
          <li class="nav-item" role="presentation">
            <button class="nav-link <%= 'active' if active_level(current_user) == level %>" id="<%= level %>-tab" data-bs-toggle="tab" data-bs-target="#<%= level %>" type="button" role="tab" aria-controls="<%= level %>" aria-selected="true"><%= level.capitalize %></button>
          </li>
        <% end %>
      </ul>
      <div class="tab-content" id="myTabContent">
        <% User.levels.keys.each do |level| %>
          <%= render 'level_leaderboard', active: active_level(current_user) == level, level: level %>
        <% end %>
      </div>
  </div>
  </div>
</div>

app/views/leaderboard/show.html.erb
<%= turbo_frame_tag "#{params[:level]}_leaderboard" do %>
  <table class="table table-borderless">
    <thead>
    <tr>
      <th>Rank</th>
      <th>Username</th>
      <th>Points</th>
      <th>Total Duels</th>
    </tr>
    </thead>
    <% @users_ranking.each do |user_ranking| %>
      <tr class="<%= "table-primary" if current_user&.username == user_ranking.username %>">
        <td><%= user_ranking.rank %></td>
        <td><%= user_ranking.username %></td>
        <td><%= user_ranking.points %></td>
        <td><%= user_ranking.duels.size %></td>
      </tr>
    <% end %>
  </table>
<% end %>