config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get 'user_levels/edit', as: 'edit_user_level'
  patch 'user_levels/update', as: 'update_user_level'

  post 'matchmaking', to: 'matchmaking#create', as: 'create_matchmaking'
  delete 'matchmaking', to: 'matchmaking#destroy', as: 'destroy_matchmaking'

  resources :duel_problems, only: [:index]

  resources :duels do
    resources :submissions, only: %i[new create]
    get 'summary', on: :member, to: 'summaries#show'
  end

  resources :problem_sets do
    resources :problems, except: %i[index show]
  end

  resources :custom_duels, only: %i[index new create show] do
    resources :participants, only: %i[create destroy], controller: 'custom_duel_participants'
  end

  get 'history', to: 'user_duels#index', as: 'history'
  get 'join/:id', to: 'custom_duel_join#show', as: 'join_custom_duel'
  patch 'start/:id', to: 'custom_duel_start#update', as: 'start_custom_duel'

  get 'settings', to: 'settings#show', as: 'settings'
  get 'leaderboard', to: 'leaderboard#index', as: 'leaderboard'
  get 'leaderboard/:level', to: 'leaderboard#show', as: 'level_leaderboard'
  get 'static_pages/index'

  root 'static_pages#index'
end

app/models/custom_duel.rb
# frozen_string_literal: true

class CustomDuel < Duel
  MAX_PARTICIPANTS = 20

  belongs_to :problem_set, optional: true
  belongs_to :leader, class_name: 'User', optional: true

  validates :extra_points, numericality: { less_than_or_equal_to: 5, greater_than_or_equal_to: 0 }

  before_create :set_invitation_code
  after_update_commit :broadcast_match_starting, if: -> { state_previously_changed?(to: 'ongoing') }
  after_update_commit :assign_problems, if: -> { ongoing? && problems.empty? }

  def set_invitation_code
    loop do
      self.invitation_code = SecureRandom.hex(4)
      break unless self.class.exists?(invitation_code: invitation_code)
    end
  end

  def assign_problems
    CustomDuelProblemsService.call(duel: self)
  end

  def broadcast_state_change
    Broadcasters::CustomDuels::DuelStateBroadcaster.broadcast_to(self)
  end

  def broadcast_match_starting
    Broadcasters::CustomDuels::MatchStartingBroadcaster.broadcast_to(self)
  end

  def custom?
    true
  end

  def time_to_start
    (start_at - Time.zone.now).ceil
  end
end

app/controllers/custom_duels_controller.rb
# frozen_string_literal: true

class CustomDuelsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_user_level, only: %i[show new]

  def index
    @duels = CustomDuel.starting.includes(:users)
  end

  def show
    @duel = CustomDuel.find_by(id: params[:id])

    return redirect_to root_path, alert: I18n.t('errors.messages.duel_not_found') if @duel.nil?

    @participant = @duel.duel_participants.find_by(user: current_user)
  end

  def new
    @duel = CustomDuel.new
  end

  def edit
    @duel = CustomDuel.find_by(id: params[:id])
  end

  def create
    @duel = CustomDuelService.call(current_user, options: duel_params)

    if @duel.errors.blank?
      redirect_to custom_duel_path(@duel)
    else
      redirect_to custom_duels_path, alert: @duel.errors.full_messages.join(', ')
    end
  end

  def update
    @duel = CustomDuel.find_by(id: params[:id])

    if @duel.update(duel_params)
      redirect_to custom_duel_path(@duel)
    else
      redirect_to custom_duels_path, alert: @duel.errors.full_messages.join(', ')
    end
  end

  private

  def duel_params
    params.require(:custom_duel).permit(:private, :problem_set_id, :extra_points)
  end
end

app/views/custom_duels/_duel.html.erb
<div class="container mt-5">
  <div class="row row-cols-1 mb-3 mt-3">
    <%= tag.div id: 'duel' do %>
      <%= turbo_frame_tag dom_id(duel), src: duel_problems_path(duel_id: duel.id), target: :_top %>
    <% end %>
  </div>
</div>

app/views/custom_duels/_duel_points.html.erb
<div id="custom-duel-<%= duel.id %>-user-<%= user.id %>-points">
  <div class="row">
    <div class="ratings text-center py-4">
      <span class="badge bg-success"><%= duel.user_state(user).points %></span>
      <span class="d-block about-rating">Duel Points</span>
    </div>
  </div>
</div>

app/views/custom_duels/_duel_progress.html.erb
<%= tag.div id: "#{dom_id(duel)}_progress" do %>
  <div class="container mt-5">
    <div class="card">
      <%= render 'duel_points', duel: duel, user: user %>
      <%= render 'participants_progress', duel: duel %>
    </div>
  </div>
<% end %>

app/views/custom_duels/_form.html.erb
<%= form_for @duel do |f| %>
  <%= render 'shared/errors', resource: @duel %>

<!--  <div class="mb-3">-->
<!--    <div class="form-check">-->
      <%#= f.check_box :private, { class: 'form-check-input' }, true, false %>
<!--      <label class="form-check-label" for="flexCheckDefault">-->
<!--        Private?-->
<!--      </label>-->
<!--    </div>-->
<!--  </div>-->

  <div class="mb-3">
    <%= f.label :problem_set %>
    <%= f.collection_select :problem_set_id, current_user.problem_sets_with_problems, :id, :detailed_name, { include_blank: 'Select a problem set' }, { required: true, class: 'form-control' }  %>
  </div>

  <div class="mb-3">
    <%= f.label :extra_points %>
    <%= f.number_field :extra_points, min: 0, max: 5, required: true, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= f.submit "Save", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/custom_duels/_match_starting.html.erb
<div class="alert alert-info" role="alert">
  <div class="d-flex justify-content-center mt-1 mb-2">
    <div class="spinner-border" role="status">
      <span class="visually-hidden">Loading...</span>
    </div>
  </div>

  <div class="d-flex justify-content-center">
    <div data-controller="timer"
         data-timer-url-value="<%= custom_duel_path(duel_id) %>"
         data-timer-duration-value="<%= duration %>">
      <h5>Starting in ... <span data-timer-target="timer"></span></h5>
    </div>
  </div>
</div>

app/views/custom_duels/_participants.html.erb
<ul class="list-group">
  <% duel.users.each do |user| %>
    <li class="list-group-item d-flex justify-content-between align-items-center">
      <%= user.username %> (<%= user.level %>)
      <span class="badge bg-primary rounded-pill"><%= user.points %></span>
    </li>
  <% end %>
</ul>

app/views/custom_duels/_participants_progress.html.erb
<div id="custom-duel-<%= duel.id %>-participants-progress">
  <div class="row">
    <div class="col-md-12">
      <div class="rating-progress-bars p-3">
        <div class="progress-1 align-items-center">
          <% problems_count = duel.problems.size %>
          <% duel.users.each do |user| %>

            <span><%= user.username %></span>
            <% user_state = duel.user_state(user) %>
            <%= custom_duel_progress(problems_count: problems_count,
                                     correct_answers: user_state.correct_answers,
                                     points: user_state.points,
                                     answered_questions: user_state.submissions) %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/custom_duels/_starting.html.erb
<div id="starting_countdown"></div>

<div class="d-flex">
  <div class="col-5">
    <h3>Custom Duel #<%= duel.id %></h3>

    <ul>
      <li>Complexity: <%= duel.complexity.capitalize %></li>
      <li>Problems: <%= duel.problem_set.problems.count %></li>
      <li>Total points: <%= duel.problem_set.problems.sum(:points) %></li>
    </ul>
    <div class="d-flex justify-content-center" id="duel-actions">
      <% if current_user == duel.leader %>
        <%= button_to "start Duel", start_custom_duel_path(duel), method: :patch, class: 'btn btn-success mx-1', id: 'duel-start-button' %>
      <% end %>

      <% if @participant %>
        <%= button_to "leave", custom_duel_participant_path(duel, @participant.id), method: :delete, class: 'btn btn-danger', id: 'duel-leave-button mx-1' %>
      <% end %>
    </div>
  </div>

  <div class="d-flex" style="height: 200px;">
    <div class="vr"></div>
  </div>

  <div class="offset-1 col-6">
    <h5>Participants:</h5>
    <div id="custom-duel-<%= duel.id %>-participants">
      <%= render 'participants', duel: duel %>
    </div>

    <div class="d-flex justify-content-center">
      <% if @participant %>
        <button type="button"
                class="btn btn-primary mx-1 my-3"
                id="clipboard-btn"
                data-controller="clipboard"
                data-clipboard-text="<%= join_custom_duel_url(duel, code: duel.invitation_code) %>"
                data-bs-toggle="tooltip" data-bs-placement="top"
                data-bs-title="Copied!">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-link-45deg" viewBox="0 0 16 16">
            <path d="M4.715 6.542 3.343 7.914a3 3 0 1 0 4.243 4.243l1.828-1.829A3 3 0 0 0 8.586 5.5L8 6.086a1.002 1.002 0 0 0-.154.199 2 2 0 0 1 .861 3.337L6.88 11.45a2 2 0 1 1-2.83-2.83l.793-.792a4.018 4.018 0 0 1-.128-1.287z"></path>
            <path d="M6.586 4.672A3 3 0 0 0 7.414 9.5l.775-.776a2 2 0 0 1-.896-3.346L9.12 3.55a2 2 0 1 1 2.83 2.83l-.793.792c.112.42.155.855.128 1.287l1.372-1.372a3 3 0 1 0-4.243-4.243L6.586 4.672z"></path>
          </svg>
          Invite
        </button>
      <% else %>
        <span class="mt-3">This duel is by invitation only.</span>
      <% end %>
    </div>
  </div>
</div>

app/views/custom_duels/edit.html.erb
<div class="row row-cols-2 mb-3">
  <div class="offset-3">
    <div class="mb-3">
      <h3>Edit custom duel</h3>
    </div>

    <%= render 'form' %>
  </div>
</div>

app/views/custom_duels/index.html.erb
<%= link_to 'create a custm duel', new_custom_duel_path, class: 'btn btn-primary mb-3' %>

<table class="table table-borderless">
  <thead>
  <tr>
    <th>ID</th>
    <th>Type</th>
    <th>Created at</th>
    <th>Participants</th>
    <th>Actions</th>
  </tr>
  </thead>
  <% @duels.each do |duel| %>
    <tr>
      <td><%= duel.id %></td>
      <td><%= duel.private? ? 'Invitation-only' : 'Public' %></td>
      <td><%= date_format(duel.created_at) %></td>
      <td><%= duel.users.size %></td>
      <td><%= link_to "Details", custom_duel_path(duel), class: 'btn btn-primary' %></td>
    </tr>
  <% end %>
</table>

app/views/custom_duels/new.html.erb
<div class="row row-cols-2 mb-3">
  <div class="offset-3">
    <div class="mb-3">
      <h3>Create a custom duel</h3>
    </div>

    <% if current_user.problem_sets_with_problems.empty? %>
      <div class="alert alert-danger" role="alert">
        <span>To set up a custom duel, ensure you have a problem set that contains a minimum of one problem.</span>
      </div>
      <%= link_to 'To my problem sets', problem_sets_path, class: 'btn btn-primary' %>
    <% else %>
      <%= render 'form' %>
    <% end %>
  </div>
</div>

app/views/custom_duels/show.html.erb
<%= turbo_stream_from "custom_duel_#{@duel.id}" %>

<% if @duel.starting? %>
  <%= render 'custom_duels/starting', duel: @duel %>
<% else %>
  <% if @duel.start_at > Time.zone.now %>
    <%= render 'custom_duels/match_starting',
              duel_id: @duel.id,
              duration: @duel.time_to_start %>
  <% else %>
    <div class="row">
      <div class="col-4">
        <%= render 'custom_duels/duel_progress', duel: @duel, user: current_user %>
      </div>

      <div class="col-8">
        <%= render 'custom_duels/duel', duel: @duel %>
      </div>
    </div>
  <% end %>
<% end %>